apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EY3dOekl3TURVek1sb1hEVE0xTURjd05USXdNVEF6TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTERMCjdoMGpqMXhBeFlJL0s0eXJoU1U0Zy9kZ3dEMnMrSlIvNzU1QTNZN2RqcmYyMGFFb0d3WUhtb3VybVFVbzZwVlIKVm54dmJERG4waWhaOVgvOHJSRmZiU3RuZE9vbXRMVS92RytnUDdFSGZPM0Z6UmV2RHhCUlRUNkhhS3BoUHlDdgowMTk5SmRaR2o0WklmR3pZdE5XbXZPb0RHOTlOU084SS9xYWJqeWQ1OUN3cnAwcnJFcmd2MzBVMHk5Qk5TSHBECmFyK1MwNGVlc0E0ek5iSktrTDNUa2dDcVg2KzU4VXJPcGJmU1FUTitzbG5XR2xWdGY2NmZxK2NmbEFLU3FhcjgKMzlWQmFybkdKMkx0V0dHMDhVbnVjM001RWkzMFhvMnZzZGU3MmhwVUhFSE9tZEQwZkxRbkU3cGx4citKMVdKWQp3WjZ6dTdvK0FLT0RUTXMxbHE4Q0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSDBXemR5bmRMU0tFclplQkNOaHVOUVZrb09ITUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQXpGK3RuLzJJYWk0dEt3Q0hTS0JiZklwNkpqR0UwT0l6TnlCbk5xSVdyOGhmdwpma0FJQ3VKRUMvaGVMeGM2d3I3Qk9nQlZlV2hESnpvaDVhSTNSd1dwNmRGNmJjTFVCRmh1dzUxRDhDRTN4VE5TCnp3dXZwdzRyVWd0dmVhZWYveXBEU0FCRzF5cEc1MzVJL1B3L0xBU1pRODFZOGI2WDl0WW1XZmtSa3k0V2FyeUoKVXdYZi9vUVBITWg2VWY3Q29yaEJZVW9WeU42UFc1TFY4RmtLZzlFRFAzRkVVck0xd3lhY1VFYktkc2YyZllWUgpiam8yaGpNZTJ5NlpZSTF3Y2R3cVlCTmhqM241dW9XRU5LWTBxb3UyQVVEWWdFL2tzL0ZQK1F5UUtQQjNZMlN2Cmx3UTJJWjVFSk9Ua2pNTWV5ODFPOFdtemZqUHdMcVgyK0NYYW5rRHMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://central.prod.eu-central.k8s.famedly.net:443
    name: central.prod
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1EZ3lOVEUxTlRneE9Gb1hEVE0xTURneU16RTJNRE14T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGo3CmhBTEJyWTc3MzJYMVhYakR4b0U2eXlNeCtnT0VXVHRyOVdIUXErcjhFRHE3WmhyZ3VUanVOcTFpSU1DWUp2MWwKeTFMd1A1bXdvWjUremtmVTM0M0ZrOGc4Vmp3eHR4K0gyNUhSSlEvOCtLZm1BNHZHWmd3OWhMM2NseTFlZk9DeAo0ZUJISTd3UXhrZzhWWkNVdnMzdHJLTWt3V3AvZ1J6SnMvbkRiOXFZZlpqdGNBSGVEQk83VnpUem5ydG93Qks2CkFoVVlBSWQ0YnR1WU4za0RRMEQ3WThveS85dWdWV1o2T01GeitKeVV6YkI0YitHMWdGT1o2N0JKYUhZZ2RWazEKUGxmcTZnVGZXMjdYU0JvQzFYK0hIMi9xWm9lTG1MRHVpZ29BclpLV251a0ZzUXFNc1NxUEh4c2tMWkJkZnZNbgo0ZjZBL204aXFRVHJUN2J4dngwQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGSU9vU2VzSlBLTllBZ1J1WTRRMmlPZ2VpRElTTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQjVKNnZwMjNMMnZQZVJzb3VtTGROOSt6aTNXNmdod3UvM1hoUExvYzRUS3hzYgpIVlpkaUhOZWxMYk1MalZ5NzQrVHk2S2ZmcjJaeERQRjZPb2xiWmFoUUxqZjN5cFd6SVdVYldkTmp4ZG54MUZNCmxseFR5cklFbnBrS2N3UnJNT3ZEcUFYVU5laWFQNE5TTFViUUQ0Z3VFQnVPV2VtcENRM2RPa2hDcm8rZkpiNjgKd2p5eW5SWjhydy8xTk1GWGY2dENLa3FrUytDVVZTRVlUMnBCUCtBbGRaejU4SFFuZi9KU1pVYzFUakRRYlZEMgozdGRGOVRoa2huMDJGUTNHdXJOTElxQzFDSDZVTEsrQ3lqN1cvcGdleXB5b2VEbUVDeFAyQytVdWtlanV2WHlYCmpDbmVkWEJsT21leHo3eUxGOVdUUFFvY29HRDJaeTBHSElVQi94TCsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://gedisa.dev.eu-central.k8s.famedly.net:443
    name: gedisa.dev
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1Ea3hNREEyTXpnek1sb1hEVE16TURrd056QTJORE16TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWE3CjJYYWRieFVKSHdQSGQxMTNHNHdnSGZmL0RTMEhYVitaQjRyRDEvVllDSnFEemRTN2NkeC8yY245a3Z0VHA3UjgKakFVWUdkbndaTkdiWlZSY2xVZEMraWhTTFlMdU1kallWcWFyU3VmbVZlQ3lHcTFLQnNkTFpOcmpMU2RTL2o3awo1ZEZBL0Y2WmYzSzBlV3RZeDhJWTliQjQ0ZXgyY29ZOU1HTjV6WEUyZCs3Wm8wSVVCWXcxWHB1ODdYZFdlSzJJCjhpR0xxdVZFcGRac0lvZEJNZk4yWTVLK3JXVmJyQUhpWXB5U0llNkVyLzlpYU5nS2hndjlQanlBRFBHNEtFc2YKTjg3UDNWK2d4eG1VNzVVRUQwTjFXdXB3YkRLekVYY0JwajJ1QXF2MzA4SVM5ZzNwRE1oUVFKUDc5NjBFMUpqVwpOKzJWQzREZkY4K2FsUEF1S1VNQ0F3RUFBYU5GTUVNd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGTVdxem03TjNxUDhIL2JsMHJvaUlkK1hVdkRSTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQi9CSlNtVnB3aGhFTCtCNExicDBDVFdwYmFhL0xlTDVkdEZZL01wMnVpbXdPMQpKeWVuV0U5QWpJaTRMU1puV00yYzh2QTRkbmlMdXcwdjZrUGFjeHlIQVQ0Zk5WcFRpcURPNyt1L1hXaTZmYUMxCkNYanJjNjJxbXBWd0MwckhsU1U4eHpQckk3MHltNmVSZUJNUE5VV1k4OTc2K2pTQ1o0ZEdxc0g4aU1SMzNpT2UKd1BNQWltUTFabktXL0RpRkZoYXc3MHUrdEFOcGw4VXFuSjR4SGJIY2hpMkJ4b0M1Mzk4ZS82QVNsOVlKbG5MRwpCRFZCeFZISnpmTTZoM0lBQS9hVEtPM3JZSFlrWURVWFlkNXh0RTkvNForaXJKV1BBNzA5aFRXbHF3VWk5U25iCnhQMHppMFZteDRONjUvN1IxS3Z3UTJlS3N1d3ZqQ3ZMdnZ5Y3RUNTgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://autopilot-1.autopilot-prod.k8s.syself.net:443
    name: syself-autopilot-1
contexts:
contexts:
  - context:
      cluster: central.prod
      user: oidc-central.prod
    name: central.prod
  - context:
      cluster: gedisa.dev
      user: oidc-gedisa.dev
    name: gedisa.dev
  - context:
      cluster: syself-autopilot-1
      user: oidc-autopilot-1
      namespace: org-famedly
    name: syself-autopilot-1
kind: Config
preferences: {}
users:
  - name: oidc-autopilot-1
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --token-cache-storage=disk
          - --oidc-issuer-url=https://id.syself.com
          - --oidc-client-id=231152229376147891@autopilot-1
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
  - name: oidc-central.prod
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://auth.cloud.famedly.net
          - --oidc-client-id=334066044769470879
        command: kubectl
        interactiveMode: IfAvailable
  - name: oidc-gedisa.dev
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://auth.cloud.famedly.net
          - --oidc-client-id=336513897374745471
        command: kubectl
        interactiveMode: IfAvailable
